// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $("[data-toggle='tooltip']").tooltip({
      container: "body",
      placement: "auto bottom"
    });
  });

}).call(this);

//# sourceMappingURL=flatty.map
